# This schema file is automatically generated by `rake db:schema`.
# It will be overwritten periodically so do not make changes.
Sequel.migration do
  change do
    create_table(:groups) do
      primary_key :id
      String :fb_id, :size=>255
      String :name, :size=>255
      String :fb_url, :size=>255
    end
    
    create_table(:postings) do
      primary_key :id
      Integer :group_id
      String :fb_id, :size=>255
      String :created_time, :size=>255
      String :updated_time, :size=>255
      String :message, :size=>255
      String :name, :size=>255
      String :attachment_url, :size=>255
      String :attachment_title, :size=>255
      String :attachment_description, :size=>255
    end
    
    create_table(:schema_info) do
      Integer :version, :default=>0, :null=>false
    end
  end
end
